#spring:
#  mvc:
#    problemdetails:
#      enabled: true
#
#  mongodb:
#    uri: mongodb://root:bN9YnKmbvdOnoERfmzdG3ePr1O1sRt5sn72WMtHwp-zuwi7D@39a1c3d3-36bb-4887-a87e-7f4bdbbd750f.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
#
#server:
#  port: 0
#
#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    # Added authSource and maxIdleTimeMS to ensure the connection stays alive
    uri: mongodb://root:bN9YnKmbvdOnoERfmzdG3ePr1O1sRt5sn72WMtHwp-zuwi7D@39a1c3d3-36bb-4887-a87e-7f4bdbbd750f.asia-southeast1.firestore.goog:443/db-capstone?tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false&authSource=admin&maxIdleTimeMS=15000

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}